### PR TITLE
Release340

### PR DESCRIPTION
**Pull request by kaitlynmortimer**

### CODE REVIEW

**Comment by SteveFeldman** [comment]
With regards to...

```
(We fixed a few of our own while we were in the area, too.)
```
Shouldn't it read...

```
We fixed a few of our own bugs while we were at it too.

**Comment by SteveFeldman** [comment]
Shouldn't we group related areas? For example, you have (2) syslog bullets, but they are several bullet points away.

**Comment by SteveFeldman** [comment]
Can we change...

```
Use our new integration to export vulnerabilities from Contrast directly into Visual Studio Team Services or Team Foundation Server.
```
to

```
Created a brand new integration to export vulnerabilities from Contrast directly into Visual Studio Team Services or Team Foundation Server.
```

**Comment by SteveFeldman** [comment]
Can we add links for OpenDocs articles for things like...

```
Looking to move to a distributed setup of Contrast? Use ZooKeeper!
```

use this link: https://docs.contrastsecurity.com/installation-setupinstall.html#zookeeper

**Comment by SteveFeldman** [comment]
Didn't we add OpenDocs for for NodeJS and Cloud Foundry?

https://docs.contrastsecurity.com/installation-nodeinstall.html#node-install-bluemix

**Comment by kaitlynmortimer** [comment]
@SteveFeldman 
 
This is the only Cloud Foundry doc at the moment:  
https://docs.contrastsecurity.com/installation-javainstall.html#cloud

Updated items based on other comments, including a couple of docs links.

**Pull request merged**
