### PR TITLE
update generic webhook

### PR DESCRIPTION
**Pull request by kristianamitchellcontrastsecurity**
Culmination of the tickets CONTRAST-39198 and CONTRAST-39200 to add extra access fields to the generic webhook

### CODE REVIEW

**Comment by gdvdsn-contrast** [comment]
@kristianamitchellcontrastsecurity I can go ahead and get this published, if it's ready to go out?

**Comment by kristianamitchellcontrastsecurity** [comment]
@gdvdsn-contrast there is one more in PR that has not been merged yet. Can I @ you when its officially merged then it can be published just to be cautious if it somehow gets pushed back.

**Comment by gdvdsn-contrast** [comment]
Sounds good, just @ me when you're ready! @kristianamitchellcontrastsecurity

**Comment by kristianamitchellcontrastsecurity** [comment]
@gdvdsn-contrast just merged to develop so this PR is good to go! Thank you!

**Comment by gdvdsn-contrast** [comment]
@kristianamitchellcontrastsecurity We've been investigating a bitbucket pipeline failure - once that's fixed, I'll get this published.

**Comment by gdvdsn-contrast** [comment]
These changes have been published: https://docs.contrastsecurity.com/admin-orgintegrations.html#webhook.

**Pull request merged**
