### PR TITLE
CONTRAST 38752 Visual Studio for Mac docs

### PR DESCRIPTION
**Pull request by gdvdsn-contrast**
Documentation and images for the the VS for Mac plugin.

### CODE REVIEW

**Comment by gdvdsn-contrast** [comment]
@gmoore This should be about ready to publish, if you think it's ready?

**Comment by contrast-product** [comment]
@gdvdsn-contrast I think we should crop the VSforMac_credentials.png image to exclude the background

**Comment by gdvdsn-contrast** [comment]
@contrast-product @gmoore Fixed the image. Let me know if you have any other comments. I'll be out next week and would like to get this published today or tomorrow. Thanks!

**Comment by contrast-product** [comment]
@gdvdsn-contrast all good for me

**Comment by gdvdsn-contrast** [comment]
https://docs.contrastsecurity.com/tools-ide.html#vsformac

**Pull request merged**
