### PR TITLE
Changes for bamboo 1.4

### PR DESCRIPTION
**Pull request by serge17**

### CODE REVIEW

**Comment by gmoore** [comment]
@kaitlynmortimer Hold this. We might be adding more to it.

**Comment by serge17** [comment]
@kaitlynmortimer Can you please check the last commit?

**Comment by kaitlynmortimer** [comment]
@serge17 The updates look good; but, I'd remove the red arrows from the images. If we need to highlight specific areas in the images, I can help with that in Photoshop.

**Comment by serge17** [comment]
@kaitlynmortimer Here are the screenshots:

bamboo_add_profile_success
bamboo_plugin_uploaded
bamboo_teamserver_profile

**Comment by gmoore** [comment]
@kaitlynmortimer We'll be releasing1.4 shortly. Merge this once you're good with it.

**Pull request merged**
