### PR TITLE
Java server copy edits

### PR DESCRIPTION
**Pull request by kaitlynmortimer**

### CODE REVIEW

**Comment by evamill** [comment]
@gilday These docs changes look mostly like style updates to the Server Configuration section of the Open Docs for Java. They have older dates on them, but Kaitlyn set them to merge before leaving last week. They look fine to go, in my opinion. Who can make sure these go out?

**Comment by gilday** [comment]
@evamill anyone familiar with the Open Docs project should be able to deploy these changes. We will need a corresponding change in the open-docs Bitbucket repository. I see Kaitlyn has such a change there from July, but it is 164 commits behind. Because the changes are so old, I am hesitant to blindly deploy these. I will work with the Java team to get these deployed next sprint.

**Comment by evamill** [comment]
I've been asking to have access to docs in BitBucket for a week--can't see them. No one seems to be able to help me with that, despite many requests to IT and some to engineering. In the notes Kaitlyn left last week, she didn't explain why/when we would use BitBucket vs GitHub or what the relationship is between the two. So, I'm in the dark on this for two reasons, then.

**Comment by terra4383** [comment]
Updated this branch with the latest from master and verified it could be merged with @gilday

**Pull request merged**
