### PR TITLE
Add Contrast Service options to NodeConfig.MD

### PR DESCRIPTION
**Pull request by ao10**
This PR is to add documentation for configuration options for the Node Agent's integration efforts with Contrast Service (external name) / Speedracer (internal name).

### CODE REVIEW

**Comment by evamill** [comment]
@cixel We would normally review this before you merge it, but the changes look mostly like code. Are you planning to merge this for the Dec 23 release?

**Comment by cixel** [comment]
This looks like documentation for config options being added for the node agent's new integration with Speedracer. I'd assume it has to be out with that release.

Note for future reference: I work on the Go agent now and so I'm not really familiar with logistical needs of Node anymore. Please include Michael Woytowitz for this kind of thing from now on. (I'll send him this thread so he can add himself)

**Comment by ao10** [comment]
Hi, sorry for the lack of context. I left the PR open and forgot to update PR description afterwards.

Ehden is correct. This PR is to add documentation for configuration options for the Node Agent's integration efforts with Contrast Service (external name) / Speedracer (internal name).

**Comment by gdvdsn-contrast** [comment]
This doc has been published here: https://docs.contrastsecurity.com/installation-nodeconfig.html#node-config.

**Pull request merged**
